openapi: 3.0.0
info:
  title: 'Crowdin API v1'
  description: "(Unofficial) OpenAPI schema for the v1 Crowdin API."
  version: ''
paths:

  '/api/project/{projectIdentifier}/add-directory':
    post:
      summary: 'Add a directory to your project.' 
      operationId: api.projects.directories.add
      externalDocs:
        url: 'https://support.crowdin.com/api/add-directory/'
      responses:
        '200':
          description: 'Added a directory to your project.'
      parameters:
        -
          name: projectIdentifier
          in: path
          required: true
        -
          name: key
          in: query
          required: true
        -
          name: name
          description: Directory name (with path if nested directory should be created).
          in: query
          required: true
        -
          name: recursive
          description: Create directories recursively if a nested name is provided. Default is false
          in: query

  '/api/project/{projectIdentifier}/add-file':
    post:
      summary: 'Add one or many files to your project.'
      operationId: api.projects.files.add
      externalDocs:
        url: 'https://support.crowdin.com/api/add-file/'
      responses:
        '200':
          description: 'Added file(s) to your project.'
      parameters:
        -
          name: projectIdentifier
          in: path
          required: true
        -
          name: key
          in: query
          required: true
      requestBody:
        content:
          application/json:
            schema:
              required:
                - files
              properties:
                files:
                  description: 'Filenames to include'
                  type: object

  '/api/project/{projectIdentifier}/update-file':
    post:
      summary: 'Update one or many files in your project.'
      operationId: api.projects.files.update
      externalDocs:
        url: 'https://support.crowdin.com/api/update-file/'
      responses:
        '200':
          description: 'Updated file(s) in your project.'
      parameters:
        -
          name: projectIdentifier
          in: path
          required: true
        -
          name: key
          in: query
          required: true
      requestBody:
        content:
          application/json:
            schema:
              required:
                - files
              properties:
                files:
                  description: 'Filenames to include'
                  type: object

  '/api/project/{projectIdentifier}/info':
    post:
      summary: 'Get project details.'
      operationId: api.projects.getDetails
      externalDocs:
        url: 'https://support.crowdin.com/api/info/'
      parameters:
        -
          name: projectIdentifier
          in: path
          required: true
        -
          name: key
          in: query
          required: true
      responses:
        '200':
          description: 'Got project details.'